# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41d90f671730f9d5c540066c268b4d8924a87f66d6be42461ffe33d5d874968b4308406635ae8337f0364f488bf82cbc08625155e65911bd72fe0dda1e9a7d4b

test:
  secret_key_base: 042195d65cf9cd78ad40352834faead32e6bd7d238d669dd22d2b13654c74c164793e2266fa0e616e9122a9633ece509fef1e8680289662864299800e7d759de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
